-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Waktu pembuatan: 24 Nov 2019 pada 19.54
-- Versi server: 5.7.28-log
-- Versi PHP: 7.2.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `randssto_rands`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `tb_kategori`
--

CREATE TABLE `tb_kategori` (
  `id_kategori` int(5) NOT NULL,
  `kd_kategori` varchar(5) NOT NULL,
  `nm_kategori` varchar(50) NOT NULL,
  `permalink` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `tb_kategori`
--

INSERT INTO `tb_kategori` (`id_kategori`, `kd_kategori`, `nm_kategori`, `permalink`) VALUES
(3, 'BL', 'BLOUSE', 'blouse'),
(4, 'KJ', 'KEMEJA', 'kemeja'),
(5, 'MX', 'MAXI', 'maxi'),
(6, 'GM', 'GAMIS', 'gamis'),
(7, 'LG', 'LONG ROMPI', 'long-rompi'),
(8, 'PT', 'PANTS', 'pants'),
(9, 'SW', 'SWEATER', 'sweater'),
(10, 'TN', 'TUNIK', 'tunik'),
(11, 'JK', 'JAKET', 'jaket'),
(12, 'ST', 'SETELAN', 'setelan'),
(13, 'BT', 'BAJU TIDUR', 'baju-tidur'),
(14, 'JS', 'JUMPSUIT', 'jumpsuit'),
(15, 'CP', 'COUPLE', 'couple'),
(16, 'KO', 'KAOS', 'kaos'),
(17, 'LD', 'LONG DRESS', 'long-dress'),
(18, 'CG', 'CARDIGAN', 'cardigan'),
(19, 'BZ', 'BLEZER', 'blezer');

-- --------------------------------------------------------

--
-- Struktur dari tabel `tb_login`
--

CREATE TABLE `tb_login` (
  `id_login` int(5) NOT NULL,
  `nama_lengkap` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `no_hp` varchar(15) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `role` enum('SA','ADMIN') NOT NULL,
  `active` enum('Aktif','Tidak Aktif') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `tb_login`
--

INSERT INTO `tb_login` (`id_login`, `nama_lengkap`, `email`, `no_hp`, `username`, `password`, `role`, `active`) VALUES
(1, 'Saepul Anwar', 'aasaepul7@gmail.com', '6282325242564', 'aasaepul', '6fe5ffcd105782504861cb610f31f044', 'SA', 'Aktif'),
(2, 'Rahmat Danil', 'rahmat@gmail.com', '082325242564', 'rahmat', '33fcf8796a48e9120f2198a32290de8f', 'SA', 'Aktif'),
(3, 'Dalwansyah', 'Dalwansyah@gmail.com', '081277061804', 'Dalwan', 'fb5689c116d7b2bdb0b2f28b844a002b', 'ADMIN', 'Aktif');

-- --------------------------------------------------------

--
-- Struktur dari tabel `tb_newsletter`
--

CREATE TABLE `tb_newsletter` (
  `id_newsletter` int(11) NOT NULL,
  `email` varchar(100) NOT NULL,
  `created` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Struktur dari tabel `tb_produk`
--

CREATE TABLE `tb_produk` (
  `id_produk` int(11) NOT NULL,
  `kode` varchar(10) NOT NULL,
  `warna` varchar(15) NOT NULL,
  `nm_produk` varchar(100) NOT NULL,
  `permalink` varchar(150) NOT NULL,
  `harga_normal` double NOT NULL,
  `diskon` double NOT NULL,
  `harga_publish` double NOT NULL,
  `deskripsi` text NOT NULL,
  `gambar` text NOT NULL,
  `stok` int(11) NOT NULL,
  `status` enum('Tersedia','Sold Out') NOT NULL,
  `id_kategori` int(11) NOT NULL,
  `prioritas` enum('0','1') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `tb_produk`
--

INSERT INTO `tb_produk` (`id_produk`, `kode`, `warna`, `nm_produk`, `permalink`, `harga_normal`, `diskon`, `harga_publish`, `deskripsi`, `gambar`, `stok`, `status`, `id_kategori`, `prioritas`) VALUES
(178, 'GM0001', 'NAVY', 'Agnes Dress Navy', 'agnes-dress-navy', 165000, 0, 165000, '<p><strong>Nama Produk : Agnes Dress Navy</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Navy</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>165.000</p>\r\n', '15717472811.jpeg', 36, 'Tersedia', 6, '0'),
(179, 'GM0002', 'KUNING', 'Agnes Dress Kuning', 'agnes-dress-kuning', 165000, 0, 165000, '<p><strong>Nama Produk : Agnes Dress Kuning</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kuning</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; &nbsp;:&nbsp;</strong>165.000</p>\r\n', '15717473973.jpeg', 36, 'Tersedia', 6, '0'),
(180, 'GM0003', 'CREAM', 'Agnes  Dress Cream', 'agnes-dress-cream', 165000, 0, 165000, '<p><strong>Nama Produk : Agnes Dress Cream</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cream</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; &nbsp;:&nbsp;</strong>165.000</p>\r\n', '15717474962.jpeg', 36, 'Tersedia', 6, '0'),
(181, 'GM0004', 'HITAM', 'Agnes Dress Hitam', 'agnes-dress-hitam', 165000, 0, 165000, '<p><strong>Nama Produk : Agnes Dress Hitam</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hitam</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; &nbsp;:&nbsp;</strong>165.000</p>\r\n', '15717475584.jpeg', 36, 'Tersedia', 6, '0'),
(184, 'GM0005', 'MERAH', 'Rainbow Dress Merah', 'rainbow-dress-merah', 185000, 0, 185000, '<p><strong>Nama Produk : Agnes Dress Navy</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>185.000</p>\r\n', '1571983470IMG-20191021-WA0007.jpg', 36, 'Tersedia', 6, '0'),
(185, 'GM0006', 'NAVY', 'Rainbow Dress Navy', 'rainbow-dress-navy', 185000, 0, 185000, '<p><strong>Nama Produk : Rainbow&nbsp;Dress Navy</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Navy</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>185.000</p>\r\n', '1571983709IMG-20191021-WA0005.jpg', 36, 'Tersedia', 6, '0'),
(186, 'GM0007', 'MERAH MUDA', 'Rainbow Dress Merah Muda', 'rainbow-dress-merah-muda', 185000, 0, 185000, '<p><strong>Nama Produk : Rainbow Dress Merah Muda</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>185.000</p>\r\n', '1571983835IMG-20191021-WA0004.jpg', 36, 'Tersedia', 6, '0'),
(187, 'GM0008', 'PINK', 'Rainbow Dress Cream', 'rainbow-dress-cream', 185000, 0, 185000, '<p><strong>Nama Produk : Rainbow Dress Pink</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Pink</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>185.000</p>\r\n', '1571983937IMG-20191021-WA0006.jpg', 36, 'Tersedia', 6, '0'),
(188, 'GM0009', 'MERAH MUDA', 'Marsela Dress Merah Muda', 'marsela-dress-merah-muda', 190000, 0, 190000, '<p><strong>Nama Produk : Marsela Dress Merah Muda</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1571984344IMG-20191023-WA0000.jpg', 36, 'Tersedia', 6, '0'),
(189, 'GM00010', 'MERAH', 'Marsela Dress Merah ', 'marsela-dress-merah', 190000, 0, 190000, '<p><strong>Nama Produk : Marsela Dress Merah&nbsp;</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1571984414IMG-20191023-WA0002.jpg', 36, 'Tersedia', 6, '0'),
(190, 'GM00011', 'NAVY', 'Marsela Dress Navy', 'marsela-dress-navy', 190000, 0, 190000, '<p><strong>Nama Produk : Marsela Dress Navy</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Navy</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1571984518IMG-20191023-WA0001.jpg', 36, 'Tersedia', 6, '0'),
(191, 'GM00012', 'PUTIH', 'Marsela Dress Cream', 'marsela-dress-cream', 190000, 0, 190000, '<p><strong>Nama Produk : Marsela Dress Putih</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Putih</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1571984596IMG-20191023-WA0003.jpg', 36, 'Tersedia', 6, '0'),
(192, 'GM00013', 'HITAM', 'Marsela Dress Hitam', 'marsela-dress-hitam', 190000, 0, 190000, '<p><strong>Nama Produk : Marsela Dress Hitam ( Bisa Busui)</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hitam</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1572070248IMG-20191026-WA0018.jpg', 36, 'Tersedia', 6, '0'),
(193, 'GM00014', 'MERAH', 'Marsela Dress Merah ', 'marsela-dress-merah', 190000, 0, 190000, '<p><strong>Nama Produk : Marsela Dress Merah( Bisa Busui)</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1572070637IMG-20191026-WA0017.jpg', 36, 'Tersedia', 6, '0'),
(194, 'GM00015', 'COKLAT TUA', 'Marsela Dress Coklat Tua ', 'marsela-dress-coklat-tua', 190000, 0, 190000, '<p><strong>Nama Produk : Marsela Dress Coklat Tua ( Bisa Busui)</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Coklat Tua</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1572070854IMG-20191026-WA0021.jpg', 36, 'Tersedia', 6, '0'),
(195, 'GM00016', 'COKLAT MUDA', 'Marsela Dress Coklat Muda', 'marsela-dress-coklat-muda', 190000, 0, 190000, '<p><strong>Nama Produk : Marsela Dress Coklat Muda ( Bisa Busui)</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Coklat Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1572071084IMG-20191026-WA0019.jpg', 36, 'Tersedia', 6, '0'),
(196, 'GM00017', 'CREAM', 'Marsela Dress Cream', 'marsela-dress-cream', 190000, 0, 190000, '<p><strong>Nama Produk : Marsela Dress Cream ( Bisa Busui)</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cream</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1572071180IMG-20191026-WA0020.jpg', 36, 'Tersedia', 6, '0'),
(197, 'GM00018', 'NAVY', 'Nami Dress Navy', 'nami-dress-navy', 175000, 0, 175000, '<p><strong>Nama Produk : Nami&nbsp;Dress Navy</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt&nbsp;Codorai Premium</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Navy</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1572341984IMG-20191026-WA0003.jpg', 36, 'Tersedia', 6, '0'),
(198, 'GM00019', 'KUNING', 'Nami Dress Kuning ', 'nami-dress-kuning', 175000, 0, 175000, '<p><strong>Nama Produk : Nami Dress Kuning</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kuning</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1572342159IMG-20191026-WA0005.jpg', 36, 'Tersedia', 6, '0'),
(199, 'GM00020', 'CREAM', 'Nami Dress Cream', 'nami-dress-cream', 175000, 0, 175000, '<p><strong>Nama Produk : Nami Dress Cream</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cream</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1572342274IMG-20191026-WA0004.jpg', 36, 'Tersedia', 6, '0'),
(200, 'GM00021', 'MERAH', 'Nami Dress Merah', 'nami-dress-merah', 175000, 0, 175000, '<p><strong>Nama Produk : Nami Dress Merah</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1572342338IMG-20191026-WA0006.jpg', 36, 'Tersedia', 6, '0'),
(201, 'GM00022', 'HITAM', 'Khanza Dress Hitam', 'khanza-dress-hitam', 190000, 0, 190000, '<p><strong>Nama Produk : Khanza Dress Hitam</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Mix Baby Teri Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hitam</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1572342843IMG-20191026-WA0009.jpg', 36, 'Tersedia', 6, '0'),
(202, 'GM00023', 'COKLAT TUA', 'Khanza Dress Coklat Tua', 'khanza-dress-coklat-tua', 190000, 0, 190000, '<p><strong>Nama Produk : Khanza Dress Coklat Tua</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Mix Baby Teri Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Coklat Tua</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1572343243IMG-20191026-WA0008.jpg', 36, 'Tersedia', 6, '0'),
(203, 'GM00024', 'COKLAT MUDA', 'Khanza Dress Coklat Muda', 'khanza-dress-coklat-muda', 190000, 0, 190000, '<p><strong>Nama Produk : Khanza Dress Coklat Muda</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Mix Baby Teri Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Coklat Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1572343347IMG-20191026-WA0010.jpg', 36, 'Tersedia', 6, '0'),
(204, 'GM00025', 'MERAH', 'Khanza Dress Merah', 'khanza-dress-merah', 190000, 0, 190000, '<p><strong>Nama Produk : Khanza Dress Merah</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Mix Baby Teri Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1572343407IMG-20191026-WA0011.jpg', 36, 'Tersedia', 6, '0'),
(205, 'GM00026', 'CREAM', 'Khanza Dress Cream', 'khanza-dress-cream', 190000, 0, 190000, '<p><strong>Nama Produk : Khanza Dress Cream</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Mix Baby Teri Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cream</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1572343560IMG-20191026-WA0012.jpg', 36, 'Tersedia', 6, '0'),
(206, 'GM00027', 'MERAH', 'Fatma Dress Merah', 'fatma-dress-merah', 175000, 0, 175000, '<p><strong>Nama Produk : Fatma Dress Merah (Bisa Busui)</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1572343880IMG-20191026-WA0016.jpg', 36, 'Tersedia', 6, '0'),
(207, 'GM00028', 'KUNING', 'Fatma Dress Kuning', 'fatma-dress-kuning', 175000, 0, 175000, '<p><strong>Nama Produk : Fatma Dress Kuning (Bisa Busui)</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kuning</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1572343992IMG-20191026-WA0014.jpg', 36, 'Tersedia', 6, '0'),
(208, 'GM00029', 'NAVY', 'Fatma Dress Navy', 'fatma-dress-navy', 175000, 0, 175000, '<p><strong>Nama Produk : Fatma Dress Navy&nbsp;(Bisa Busui)</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Navy</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1572344110IMG-20191026-WA0015.jpg', 36, 'Tersedia', 6, '0'),
(209, 'GM00030', 'COKLAT MUDA', 'Fatma Dress Coklat Muda', 'fatma-dress-coklat-muda', 175000, 0, 175000, '<p><strong>Nama Produk : Fatma Dress Merah (Bisa Busui)</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Codorai Premium Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Coklat Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1572344184IMG-20191026-WA0013.jpg', 36, 'Tersedia', 6, '0'),
(210, 'GM00031', 'KUNING', 'Qanita Dress Kuning', 'qanita-dress-kuning', 225000, 0, 225000, '<p><strong>Nama Produk : Qanita Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kuning</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>225.000</p>\r\n', '1573185597IMG-20191101-WA0003.jpg', 36, 'Tersedia', 6, '0'),
(211, 'GM00032', 'BIRU LANGIT', 'Qanita Dress Biru Langit', 'qanita-dress-biru-langit', 225000, 0, 225000, '<p><strong>Nama Produk : Qanita Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Biru Langit</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>225.000</p>\r\n', '1573185887IMG-20191101-WA0001.jpg', 36, 'Tersedia', 6, '0'),
(212, 'GM00033', 'CREAM', 'Qanita Dress Cream', 'qanita-dress-cream', 225000, 0, 225000, '<p><strong>Nama Produk : Qanita Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cream</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>225.000</p>\r\n', '1573186004IMG-20191101-WA0002.jpg', 36, 'Tersedia', 6, '0'),
(213, 'GM00034', 'MERAH MUDA', 'Qanita Dress Merah Muda', 'qanita-dress-merah-muda', 225000, 0, 225000, '<p><strong>Nama Produk : Qanita Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>225.000</p>\r\n', '1573186055IMG-20191101-WA0005.jpg', 36, 'Tersedia', 6, '0'),
(214, 'GM00035', 'HIJAU TUA', 'Salma Dress Hijau Tua', 'salma-dress-hijau-tua', 190000, 0, 190000, '<p><strong>Nama Produk : Salma Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Codorai Twil Fhanesa</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hijau Tua</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1573627729ebaa6f24-f4ef-46ca-b042-b7d63df9d3fa.jpg', 0, 'Sold Out', 6, '0'),
(215, 'GM00036', 'MERAH', 'Salma Dress Merah', 'salma-dress-merah', 190000, 0, 190000, '<p><strong>Nama Produk : Salma Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Codorai Twil Fhanesa</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1573627768ce1c914a-1df9-438e-aa4a-9e74bd38916c.jpg', 0, 'Sold Out', 6, '0'),
(216, 'GM00037', 'KUNING', 'Salma Dress Kuning', 'salma-dress-kuning', 190000, 0, 190000, '<p><strong>Nama Produk : Salma Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Codorai Twil Fhanesa</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kuning</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '15736277910a182aaa-cb40-495b-8710-9360c17ee75e.jpg', 0, 'Sold Out', 6, '0'),
(217, 'GM00038', 'BIRU', 'Salma Dress Biru', 'salma-dress-biru', 190000, 0, 190000, '<p><strong>Nama Produk : Salma Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Codorai Twil Fhanesa</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Biru</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1573627817ec7db472-8204-4b7e-bfe8-eccf161e96b9.jpg', 0, 'Sold Out', 6, '0'),
(218, 'GM00039', 'MERAH', 'Zephyra Dress Merah', 'zephyra-dress-merah', 190000, 0, 190000, '<p><strong>Nama Produk : Zephyra Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Codoray Twill Fanesa Premium Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '1573626944990fc1f2-7c93-4f23-9d8c-2a43ce2c84ed.jpg', 0, 'Sold Out', 6, '0'),
(219, 'GM00040', 'HIJAU TUA', 'Zephyra Dress Hijau Tua', 'zephyra-dress-hijau-tua', 190000, 0, 190000, '<p><strong>Nama Produk : Zephyra Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Codoray Twill Fanesa Premium Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hijau Tua</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '15736269679f9e3c14-1b3d-4f8a-ad8e-4ac21aa0ba9d.jpg', 0, 'Sold Out', 6, '0'),
(220, 'GM00041', 'ABU MUDA', 'Zephyra Dress Abu Muda', 'zephyra-dress-abu-muda', 190000, 0, 190000, '<p><strong>Nama Produk : Zephyra Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Codoray Twill Fanesa Premium Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Abu Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '157362701506f7b452-5a72-460f-bbce-9875abc3ae6d.jpg', 0, 'Sold Out', 6, '0'),
(221, 'GM00042', 'CREAM', 'Zephyra Dress Cream', 'zephyra-dress-cream', 190000, 0, 190000, '<p><strong>Nama Produk : Zephyra Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Codoray Twill Fanesa Premium Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cream</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>190.000</p>\r\n', '15736268948bc17211-bf84-4dd2-a61a-cddcdfb00d36.jpg', 0, 'Sold Out', 6, '0'),
(222, '00043', 'Orange', 'Queen Outer Orange', 'queen-outer-orange', 165000, 0, 165000, '<p><strong>Nama Produk : Queen Outer</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Semi Woll Garment Mix Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Orange</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>165.000</p>\r\n', '1573625057QUEN_KUNING.jpg', 0, 'Sold Out', 6, '0'),
(223, 'GM00044', 'HIJAU', 'Queen Outer Hijau', 'queen-outer-hijau', 165000, 0, 165000, '<p><strong>Nama Produk : Queen Outer</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Semi Woll Garment Mix Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hijau</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>165.000</p>\r\n', '1573625139queen.jpg', 0, 'Sold Out', 6, '0'),
(224, 'GM00045', 'HITAM', 'Queen Outer Hitam', 'queen-outer-hitam', 165000, 0, 165000, '<p><strong>Nama Produk : Queen Outer</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Semi Woll Garment Mix Codorai</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hitam</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>165.000</p>\r\n', '1573625102Guen_Hitam.jpg', 0, 'Sold Out', 6, '0'),
(225, 'GM00046', 'BIRU', 'Warna Dress Biru', 'warna-dress-biru', 200000, 0, 200000, '<p><strong>Nama Produk : Warna Dress Biru (Busui)&nbsp;</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Polos Cotton Toyobo Fodu&nbsp;</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Quality Mix Flanel Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Orange</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>200.000</p>\r\n', '1573307782IMG-20191109-WA0017.jpg', 0, 'Sold Out', 6, '0'),
(226, 'GM00047', 'MERAH', 'Warna Dress Merah', 'warna-dress-merah', 200000, 0, 200000, '<p><strong>Nama Produk : Warna Dress Merah&nbsp;(Busui)&nbsp;</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Polos Cotton Toyobo Fodu&nbsp;</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Quality Mix Flanel Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>200.000</p>\r\n', '1573307878IMG-20191109-WA0015.jpg', 0, 'Sold Out', 6, '0'),
(227, 'GM00048', 'KUNING', 'Warna Dress Kuning', 'warna-dress-kuning', 200000, 0, 200000, '<p><strong>Nama Produk : Warna Dress Kuning (Busui)&nbsp;</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Polos Cotton Toyobo Fodu&nbsp;</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Quality Mix Flanel Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kuning</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>200.000</p>\r\n', '1573307959IMG-20191109-WA0014.jpg', 0, 'Sold Out', 6, '0'),
(228, '00049', 'MERAH MUDA', 'Warna Dress Merah Muda', 'warna-dress-merah-muda', 200000, 0, 200000, '<p><strong>Nama Produk : Warna Dress Merah Muda (Busui)&nbsp;</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Polos Cotton Toyobo Fodu&nbsp;</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Quality Mix Flanel Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>200.000</p>\r\n', '1573308035IMG-20191109-WA0016.jpg', 36, 'Tersedia', 0, '0'),
(229, 'GM00050', 'HIJAU', 'Warna Dress Hijau', 'warna-dress-hijau', 200000, 0, 200000, '<p><strong>Nama Produk : Warna Dress Hijau (Busui)&nbsp;</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Polos Cotton Toyobo Fodu&nbsp;</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Quality Mix Flanel Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hijau</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>200.000</p>\r\n', '1573308104IMG-20191109-WA0018.jpg', 0, 'Sold Out', 6, '0'),
(230, 'GM00049', 'MERAH MUDA', 'Warna Dress Merah Muda', 'warna-dress-merah-muda', 200000, 0, 200000, '<p><strong>Nama Produk : Warna Dress Merah Muda (Busui)&nbsp;</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Polos Cotton Toyobo Fodu&nbsp;</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Quality Mix Flanel Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>200.000</p>\r\n', '1573308255IMG-20191109-WA0016.jpg', 0, 'Sold Out', 6, '0'),
(231, 'GM00051', 'HITAM', 'Veronica Dress Hitam', 'veronica-dress-hitam', 215000, 0, 215000, '<p><strong>Nama Produk : Veronica Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cotton Liner Premium Mix Semiwoll Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hitam</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>215.000</p>\r\n\r\n<p>*Pakai Ikat Pinggang Lepas</p>\r\n\r\n<p>*Resleting Belakang</p>\r\n', '157362569320c814c3-f7dc-46b0-b9d2-1970b9aa2e2a.jpg', 0, 'Sold Out', 6, '0'),
(232, 'GM00052', 'MERAH', 'Veronica Dress Merah', 'veronica-dress-merah', 215000, 0, 215000, '<p><strong>ama Produk : Veronica Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cotton Liner Premium Mix Semiwoll Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>215.000</p>\r\n\r\n<p>*Pakai Ikat Pinggang Lepas</p>\r\n\r\n<p>*Resleting Belakang</p>\r\n', '15736257304e838337-1306-4966-b2c5-ff574ed3ea75.jpg', 0, 'Sold Out', 6, '0'),
(233, 'GM00053', 'KUNING', 'Veronica Dress Kuning', 'veronica-dress-kuning', 215000, 0, 215000, '<p><strong>ama Produk : Veronica Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cotton Liner Premium Mix Semiwoll Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kuning</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>215.000</p>\r\n\r\n<p>*Pakai Ikat Pinggang Lepas</p>\r\n\r\n<p>*Resleting Belakang</p>\r\n', '1573625782e1f900c5-6371-4883-8435-a5c9b8dfbef2.jpg', 0, 'Sold Out', 6, '0'),
(234, 'GM00054', 'CREAM', 'Veronica Dress Cream', 'veronica-dress-cream', 215000, 0, 215000, '<p><strong>ama Produk : Veronica Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cotton Liner Premium Mix Semiwoll Garment</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cream</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>215.000</p>\r\n\r\n<p>*Pakai Ikat Pinggang Lepas</p>\r\n\r\n<p>*Resleting Belakang</p>\r\n', '1573626133e56b12e0-029d-404e-8a4b-8e834b0519fd.jpg', 0, 'Sold Out', 6, '0'),
(235, 'GM00055', 'BIRU MUDA', 'Monza Dress', 'monza-dress', 199000, 0, 199000, '<p><strong>Nama Produk : Monza Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;PopyCrepe</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Biru Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; : </strong>Free Size&nbsp;Fitt to XL, Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>199.000</p>\r\n', '1573704027724fd321-b301-4f76-8e4d-40626f870b8f.jpg', 36, 'Tersedia', 6, '0'),
(236, 'GM00056', 'HITAM', 'Monza Dress', 'monza-dress', 199000, 0, 199000, '<p><strong>Nama Produk : Monza Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;PopyCrepe</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hitam</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; : </strong>Free Size&nbsp;Fitt to XL, Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>199.000</p>\r\n', '15737041003e3012df-0b49-4946-846d-1377b1992cb0.jpg', 36, 'Tersedia', 6, '0'),
(238, 'GM00058', 'CREAM', 'Monza Dress', 'monza-dress', 199000, 0, 199000, '<p><strong>Nama Produk : Monza Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;PopyCrepe</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cream</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; : </strong>Free Size&nbsp;Fitt to XL, Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>199.000</p>\r\n', '1573704246973317a8-4074-4be5-9670-7bb541c36955.jpg', 36, 'Tersedia', 6, '0'),
(239, 'GM00059', 'NAVY KUNING', 'Katy Dress Navy Kuning', 'katy-dress-navy-kuning', 200000, 0, 200000, '<p><strong>Nama Produk : Katy Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cartier Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Navy Kuning</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>200.000</p>\r\n', '1573870547IMG-20191114-WA0028.jpg', 36, 'Tersedia', 6, '0'),
(240, 'GM00060', 'KUNING NAVY', 'Katy Dress Kuning Navy', 'katy-dress-kuning-navy', 200000, 0, 200000, '<p><strong>Nama Produk : Katy Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cartier Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kuning Navy</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>200.000</p>\r\n', '1573870705IMG-20191114-WA0033.jpg', 36, 'Tersedia', 6, '0'),
(241, 'GM00061', 'MERAH CREAM', 'Katy Dress Merah Cream', 'katy-dress-merah-cream', 200000, 0, 200000, '<p><strong>Nama Produk : Katy Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cartier Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah Cream</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>200.000</p>\r\n', '1573870798IMG-20191114-WA0032.jpg', 36, 'Tersedia', 6, '0'),
(242, 'GM00062', 'CREAM MERAH', 'Katy Dress Cream Merah', 'katy-dress-cream-merah', 200000, 0, 200000, '<p><strong>Nama Produk : Katy Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cartier Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cream Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>200.000</p>\r\n', '1573870866IMG-20191114-WA0030.jpg', 36, 'Tersedia', 6, '0'),
(243, 'GM00063', 'ABU HITAM', 'Katy Dress Abu Hitam', 'katy-dress-abu-hitam', 200000, 0, 200000, '<p><strong>Nama Produk : Katy Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cartier Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Abu Hitam</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>200.000</p>\r\n', '1573870941IMG-20191114-WA0029.jpg', 36, 'Tersedia', 6, '0'),
(244, 'GM00064', 'HITAM ABU', 'Katy Dress Hitam Abu', 'katy-dress-hitam-abu', 200000, 0, 200000, '<p><strong>Nama Produk : Katy Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cartier Impor</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hitam Abu</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>200.000</p>\r\n', '1573871006IMG-20191114-WA0031.jpg', 36, 'Tersedia', 6, '0'),
(245, 'GM00065', 'MOTIF', 'Siti Dress Motif', 'siti-dress-motif', 170000, 0, 170000, '<p><strong>Nama Produk : Queen Outer</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Cotun Impor Songket</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Orange</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; : </strong>170.000</p>\r\n', '1573874274IMG-20191116-WA0000.jpg', 36, 'Tersedia', 6, '0'),
(246, 'GM00066', 'MERAH', 'Lyla Dress Merah', 'lyla-dress-merah', 175000, 0, 175000, '<p><strong>Nama Produk : Lyla Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai Printing</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm&nbsp;</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574128419IMG-20191118-WA0008.jpg', 36, 'Tersedia', 6, '0'),
(247, 'GM00067', 'BIRU MUDA', 'Lyla Dress Biru Muda', 'lyla-dress-biru-muda', 175000, 0, 175000, '<p><strong>Nama Produk : Lyla Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai Printing</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Biru Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm&nbsp;</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574128527IMG-20191118-WA0007.jpg', 36, 'Tersedia', 6, '0'),
(248, 'GM00068', 'HIJAU', 'Lyla Dress Hijau', 'lyla-dress-hijau', 175000, 0, 175000, '<p><strong>Nama Produk : Lyla Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai Printing</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hijau</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm&nbsp;</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574128631IMG-20191118-WA0006.jpg', 36, 'Tersedia', 6, '0'),
(249, 'GM00069', 'MERAH MUDA', 'Lyla Dress Merah Muda', 'lyla-dress-merah-muda', 175000, 0, 175000, '<p><strong>Nama Produk : Lyla Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai Printing</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm&nbsp;</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574128696IMG-20191118-WA0001.jpg', 36, 'Tersedia', 6, '0'),
(250, 'GM00070', 'MERAH', 'Kirana Dress Merah ', 'kirana-dress-merah', 175000, 0, 175000, '<p><strong>Nama Produk : Kirana Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai Printing</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm&nbsp;</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574128811IMG-20191118-WA0005.jpg', 36, 'Tersedia', 6, '0'),
(251, 'GM00071', 'HIJAU', 'Kirana Dress Hijau', 'kirana-dress-hijau', 175000, 0, 175000, '<p><strong>Nama Produk : Kirana Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai Printing</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hijau</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm&nbsp;</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574129072IMG-20191118-WA0003.jpg', 36, 'Tersedia', 6, '0'),
(252, 'GM00072', 'BIRU MUDA', 'Kirana Dress Biru Muda', 'kirana-dress-biru-muda', 175000, 0, 175000, '<p><strong>Nama Produk : Kirana Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai Printing</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Biru Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm&nbsp;</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574129133IMG-20191118-WA0002.jpg', 36, 'Tersedia', 6, '0'),
(253, 'GM00073', 'MERAH MUDA', 'Kirana Dress Merah Muda', 'kirana-dress-merah-muda', 175000, 0, 175000, '<p><strong>Nama Produk : Kirana Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Baby Codorai Printing</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 108cm, Pj 140cm&nbsp;</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574129363IMG-20191118-WA0004.jpg', 36, 'Tersedia', 6, '0'),
(254, '00057', 'ABU MUDA', 'Monza Dress', 'monza-dress', 199000, 0, 199000, '<p><strong>Nama Produk : Monza Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;PopyCrepe</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Abu Muda</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; : </strong>Free Size&nbsp;Fitt to XL, Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>199.000</p>\r\n', '1574428685a3b8affa-611b-40bc-8571-070bb03aa03e.jpg', 36, 'Tersedia', 0, '0'),
(255, '00074', 'JEANS', 'Syahira Dress Jeans', 'syahira-dress-jeans', 175000, 0, 175000, '<p><strong>Nama Produk : Syahira Jeans</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Jeans Wash</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Jeans</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 106cm, Pj 140cm&nbsp;</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574430175IMG-20191121-WA0030.jpg', 0, 'Sold Out', 0, '0'),
(256, '00074', 'JEANS', 'Syahira Dress Jeans', 'syahira-dress-jeans', 175000, 0, 175000, '<p><strong>Nama Produk : Syahira Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Jeans Wash</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Jeans</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 106cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574452575IMG-20191121-WA0030.jpg', 0, 'Sold Out', 0, '0'),
(257, 'GM00074', 'JEANS', 'Syahira Dress Jeans', 'syahira-dress-jeans', 175000, 0, 175000, '<p><strong>Nama Produk : Syahira Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Matt Jeans Wash</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Jeans</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 106cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>175.000</p>\r\n', '1574452749IMG-20191121-WA0030.jpg', 0, 'Sold Out', 6, '0'),
(258, 'GM00075', 'MERAH', 'Davina  Dress Merah', 'davina-dress-merah', 195000, 0, 195000, '<p><strong>Nama Produk : Davina Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Victoria Mix Tory Burch</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Merah</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000 S</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat resleting di bagian depan untuk memudahkan akses ibu menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Cardigan nyatu sama gamis</p>\r\n\r\n<p>&nbsp;</p>\r\n', '1574453787IMG-20191122-WA0006.jpg', 36, 'Tersedia', 6, '0'),
(260, 'GM00077', 'HITAM', 'Davina  Dress Hitam', 'davina-dress-hitam', 195000, 0, 195000, '<p><strong>Nama Produk : Davina Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Victoria Mix Tory Burch</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Hitam</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat resleting di bagian depan untuk memudahkan akses ibu menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Cardigan nyatu sama gamis</p>\r\n', '1574453968IMG-20191122-WA0007.jpg', 36, 'Tersedia', 6, '0'),
(261, 'GM00078', 'COKLAT SUSU', 'Davina  Dress Coklat Susu', 'davina-dress-coklat-susu', 195000, 0, 195000, '<p><strong>Nama Produk : Davina Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Victoria Mix Tory Burch</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Coklat Susu</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat resleting di bagian depan untuk memudahkan akses ibu menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Cardigan nyatu sama gamis</p>\r\n', '1574454048IMG-20191122-WA0009.jpg', 36, 'Tersedia', 6, '0'),
(262, 'GM00076', 'ORANGE', 'Davina  Dress Orange', 'davina-dress-orange', 195000, 0, 195000, '<p><strong>Nama Produk : Davina Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Victoria Mix Tory Burch</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Orange</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat resleting di bagian depan untuk memudahkan akses ibu menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly</p>\r\n', '1574474226IMG-20191122-WA0008.jpg', 36, 'Tersedia', 6, '0'),
(263, 'GM00079', 'KOMBINASI WARNA', 'Zaskia Dress Kombinasi Warna', 'zaskia-dress-kombinasi-warna', 195000, 0, 195000, '<p><strong>Nama Produk : Zaskia Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cotton Madina</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kombinasi Warna</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Busui friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kantong kiri kanan</p>\r\n', '1574475633IMG-20191122-WA0010.jpg', 24, 'Tersedia', 6, '0'),
(264, 'GM00080', 'KOMBINASI WARNA', 'Zaskia Dress Kombinasi Warna', 'zaskia-dress-kombinasi-warna', 195000, 0, 195000, '<p><strong>Nama Produk : Zaskia Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cotton Madina</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kombinasi Warna</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Busui friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kantong kiri kanan</p>\r\n', '1574475690IMG-20191122-WA0011.jpg', 24, 'Tersedia', 6, '0'),
(265, 'GM00081', 'KOMBINASI WARNA', 'Zaskia Dress Kombinasi Warna', 'zaskia-dress-kombinasi-warna', 195000, 0, 195000, '<p><strong>Nama Produk : Zaskia Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cotton Madina</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kombinasi Warna</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Busui friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kantong kiri kanan</p>\r\n', '1574475747IMG-20191122-WA0012.jpg', 24, 'Tersedia', 6, '0'),
(266, 'GM00082', 'KOMBINASI WARNA', 'Zaskia Dress Kombinasi Warna', 'zaskia-dress-kombinasi-warna', 195000, 0, 195000, '<p><strong>Nama Produk : Zaskia Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cotton Madina</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kombinasi Warna</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Busui friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kantong kiri kanan</p>\r\n', '1574475823IMG-20191122-WA0013.jpg', 24, 'Tersedia', 6, '0');
INSERT INTO `tb_produk` (`id_produk`, `kode`, `warna`, `nm_produk`, `permalink`, `harga_normal`, `diskon`, `harga_publish`, `deskripsi`, `gambar`, `stok`, `status`, `id_kategori`, `prioritas`) VALUES
(267, 'GM00083', 'KOMBINASI WARNA', 'Zaskia Dress Kombinasi Warna', 'zaskia-dress-kombinasi-warna', 195000, 0, 195000, '<p><strong>Nama Produk : Zaskia Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cotton Madina</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kombinasi Warna</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Busui friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kantong kiri kanan</p>\r\n', '1574476001IMG-20191122-WA0014.jpg', 24, 'Tersedia', 6, '0'),
(268, 'GM00084', 'KOMBINASI WARNA', 'Zaskia Dress Kombinasi Warna', 'zaskia-dress-kombinasi-warna', 195000, 0, 195000, '<p><strong>Nama Produk : Zaskia Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Cotton Madina</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kombinasi Warna</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Busui friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Kantong kiri kanan</p>\r\n', '1574476060IMG-20191122-WA0015.jpg', 24, 'Tersedia', 6, '0'),
(269, 'GM00085', 'MOTIF', 'Nadine Dress Motif', 'nadine-dress-motif', 205000, 0, 205000, '<p><strong>Nama Produk : Nadine Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Victoria Print Import</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Motif</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>205.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly dengan tangan karet</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat resleting di bagian depan mempermudah akses menyusui</p>\r\n', '1574478950IMG-20191122-WA0016.jpg', 24, 'Tersedia', 6, '0'),
(270, 'GM00086', 'MOTIF', 'Nadine Dress Motif', 'nadine-dress-motif', 205000, 0, 205000, '<p><strong>Nama Produk : Nadine Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Victoria Print Import</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Motif</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>205.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly dengan tangan karet</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat resleting di bagian depan mempermudah akses menyusui</p>\r\n', '1574479023IMG-20191122-WA0017.jpg', 24, 'Tersedia', 6, '0'),
(271, '00087', 'MOTIF', 'Nadine Dress Motif', 'nadine-dress-motif', 205000, 0, 205000, '<p><strong>Nama Produk : Nadine Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Victoria Print Import</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Kombinasi Warna</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>205.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly dengan tangan karet</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat resleting di bagian depan mempermudah akses menyusui</p>\r\n', '1574479079IMG-20191122-WA0018.jpg', 24, 'Tersedia', 0, '0'),
(272, 'GM00087', 'MOTIF', 'Nadine Dress Motif', 'nadine-dress-motif', 205000, 0, 205000, '<p><strong>Nama Produk : Nadine Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Victoria Print Import</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Motif</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>205.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly dengan tangan karet</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat resleting di bagian depan mempermudah akses menyusui</p>\r\n', '1574479275IMG-20191122-WA0018.jpg', 24, 'Tersedia', 6, '0'),
(273, 'GM00057', 'GREY', 'Monza Dress', 'monza-dress', 199000, 0, 199000, '<p><strong>Nama Produk : Monza Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;PopyCrepe</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Grey</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; : </strong>Free Size&nbsp;Fitt to XL, Ld 105cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>199.000</p>\r\n', '1574485406a3b8affa-611b-40bc-8571-070bb03aa03e.jpg', 36, 'Tersedia', 6, '0'),
(274, 'GM00088', 'MERAH', 'Alinka Dress Merah', 'alinka-dress-merah', 195000, 0, 195000, '<p><strong>Nama Produk : Alinka&nbsp;Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Tory burch premium di mix dengan victoria</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu Friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Motif Flower yang classy memberikan kesan exclusif</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat pin gold di bagian dada kiri untuk mempermewah kesan dress</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat 4 (Empat) kancing motif di bagian depan untuk memudahkan akses ibu menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat rapel pada bagian bawah dress, memberikan efek lebih panjang dan flowy</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>\r\n', '1574486225IMG-20191122-WA0020.jpg', 36, 'Tersedia', 6, '0'),
(275, 'GM00089', 'HITAM', 'Alinka Dress Hitam', 'alinka-dress-hitam', 195000, 0, 195000, '<p><strong>Nama Produk : Alinka&nbsp;Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Tory burch premium di mix dengan victoria</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu Friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Motif Flower yang classy memberikan kesan exclusif</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat pin gold di bagian dada kiri untuk mempermewah kesan dress</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat 4 (Empat) kancing motif di bagian depan untuk memudahkan akses ibu menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat rapel pada bagian bawah dress, memberikan efek lebih panjang dan flowy</p>\r\n', '1574486312IMG-20191122-WA0021.jpg', 36, 'Tersedia', 6, '0'),
(276, '00090', 'ORANGE', 'Alinka Dress Orange', 'alinka-dress-orange', 195000, 0, 195000, '<p><strong>Nama Produk : Alinka&nbsp;Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Tory burch premium di mix dengan victoria</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu Friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Motif Flower yang classy memberikan kesan exclusif</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat pin gold di bagian dada kiri untuk mempermewah kesan dress</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat 4 (Empat) kancing motif di bagian depan untuk memudahkan akses ibu menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat rapel pada bagian bawah dress, memberikan efek lebih panjang dan flowy</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>\r\n', '1574486388IMG-20191122-WA0019.jpg', 36, 'Tersedia', 0, '0'),
(277, 'GM00091', 'COKLAT SUSU', 'Alinka Dress Coklat Susu', 'alinka-dress-coklat-susu', 195000, 0, 195000, '<p><strong>Nama Produk : Alinka&nbsp;Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Tory burch premium di mix dengan victoria</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu Friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Motif Flower yang classy memberikan kesan exclusif</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat pin gold di bagian dada kiri untuk mempermewah kesan dress</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat 4 (Empat) kancing motif di bagian depan untuk memudahkan akses ibu menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat rapel pada bagian bawah dress, memberikan efek lebih panjang dan flowy</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>\r\n', '1574486450IMG-20191122-WA0027.jpg', 36, 'Tersedia', 6, '0'),
(278, 'GM00091', 'ORANGE', 'Alinka Dress Orange', 'alinka-dress-orange', 195000, 0, 195000, '<p><strong>Nama Produk : Alinka&nbsp;Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Tory burch premium di mix dengan victoria</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu Friendly</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Motif Flower yang classy memberikan kesan exclusif</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat pin gold di bagian dada kiri untuk mempermewah kesan dress</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat 4 (Empat) kancing motif di bagian depan untuk memudahkan akses ibu menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat rapel pada bagian bawah dress, memberikan efek lebih panjang dan flowy</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>\r\n', '1574486582IMG-20191122-WA0019.jpg', 36, 'Tersedia', 6, '0'),
(279, 'GM00092', 'PINK', 'Lafreya Dress Pink', 'lafreya-dress-pink', 195000, 0, 195000, '<p><strong>Nama Produk : Lafreya Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Sakura Premium</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Pink</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly dengan tangan berkancing</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat kancing&nbsp;di bagian depan mempermudah akses menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Saku pada kiri dan kanan</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat tali yang mempercantik gamis dan menyesuaikan ukuran</p>\r\n', '1574487519IMG-20191122-WA0022.jpg', 36, 'Tersedia', 6, '0'),
(280, 'GM00093', 'ORANGE', 'Lafreya Dress Orange', 'lafreya-dress-orange', 195000, 0, 195000, '<p><strong>Nama Produk : Lafreya Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Sakura Premium</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Orange</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly dengan tangan berkancing</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat kancing&nbsp;di bagian depan mempermudah akses menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Saku pada kiri dan kanan</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat tali yang mempercantik gamis dan menyesuaikan ukuran</p>\r\n', '1574487604IMG-20191122-WA0023.jpg', 36, 'Tersedia', 6, '0'),
(281, 'GM00094', 'COKLAT SUSU', 'Lafreya Dress Coklat Susu', 'lafreya-dress-coklat-susu', 195000, 0, 195000, '<p><strong>Nama Produk : Lafreya Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Sakura Premium</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Coklat Susu</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly dengan tangan berkancing</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat kancing&nbsp;di bagian depan mempermudah akses menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Saku pada kiri dan kanan</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat tali yang mempercantik gamis dan menyesuaikan ukuran</p>\r\n', '1574487765IMG-20191122-WA0024.jpg', 36, 'Tersedia', 6, '0'),
(282, 'GM00095', 'BIRU MUDA', 'Lafreya Dress Biru Muda', 'lafreya-dress-biru-muda', 195000, 0, 195000, '<p><strong>Nama Produk : Lafreya Dress</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Sakura Premium</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Biru Muda&nbsp;</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly dengan tangan berkancing</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat kancing&nbsp;di bagian depan mempermudah akses menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Saku pada kiri dan kanan</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat tali yang mempercantik gamis dan menyesuaikan ukuran</p>\r\n', '1574487949IMG-20191122-WA0025.jpg', 36, 'Tersedia', 6, '0'),
(283, 'GM00096', 'ARMY', 'Lafreya Dress Army', 'lafreya-dress-army', 195000, 0, 195000, '<p><strong>Nama Produk : Lafreya Army</strong></p>\r\n\r\n<p><strong>Bahan&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Sakura Premium</p>\r\n\r\n<p><strong>Warna&nbsp; &nbsp; &nbsp;:</strong>&nbsp;Army</p>\r\n\r\n<p><strong>Ukuran&nbsp; &nbsp; :&nbsp;</strong>Ld 104cm, Pj 140cm</p>\r\n\r\n<p><strong>Harga&nbsp; &nbsp; &nbsp; :&nbsp;</strong>195.000&nbsp;</p>\r\n\r\n<p><strong>Detail&nbsp; &nbsp; &nbsp; :&nbsp;</strong>Sangat nyaman, adem, jatuh dan tidak bikin gerah</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Wudhu friendly dengan tangan berkancing</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat kancing&nbsp;di bagian depan mempermudah akses menyusui</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Saku pada kiri dan kanan</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Terdapat tali yang mempercantik gamis dan menyesuaikan ukuran</p>\r\n', '1574488157IMG-20191122-WA0026.jpg', 36, 'Tersedia', 6, '0');

-- --------------------------------------------------------

--
-- Struktur dari tabel `tb_registrasi`
--

CREATE TABLE `tb_registrasi` (
  `id_registrasi` int(10) NOT NULL,
  `nm_lengkap` varchar(50) NOT NULL,
  `no_wa` varchar(15) NOT NULL,
  `email` varchar(50) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `kriteria` enum('pembeli','reseller') NOT NULL,
  `active` enum('0','1') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `tb_registrasi`
--

INSERT INTO `tb_registrasi` (`id_registrasi`, `nm_lengkap`, `no_wa`, `email`, `username`, `password`, `kriteria`, `active`) VALUES
(2, 'Rahmat danil', '085215053503', 'rford.bkt@gmail.com', 'Rahmat297', 'ae4267d4d93a8165129fb4c9cc90ed06', 'pembeli', '1'),
(3, 'Anisa Khairul fitri', '081958253401', 'annisakhaerulfitri@gmail.com', 'Anisa k fitri', 'afd928e014d8a6d62a09dabf4c9f9d73', 'pembeli', '0'),
(4, 'Yanto ana', '081336366897', 'yanto.datun@yahoo.cok', 'Yanto', 'ce4c9bf3055a7ec261f7e7d14ca94ba2', 'pembeli', '0'),
(5, 'Yanto ana', '081336366897', 'yanto.datun@yahoo.com', 'Yanto', 'ce4c9bf3055a7ec261f7e7d14ca94ba2', 'pembeli', '1'),
(6, 'Wanty', '081281137995', 'wanty.dya@gmail.com', 'Wanty', '2a99b5afc0bb29d8abc62ce156302458', 'pembeli', '1'),
(7, 'Sofyan', '+68279344', 'sofyan.dk80@gmail.com', 'Sofyan-dk', 'c75a4bee326499c70dc4b888b9f3d0e4', 'pembeli', '1'),
(8, 'fatimah zahra', '081211106741', 'zahraf0306@gmail.com', 'zahraf', 'a6e07d79e2dd004d0fa6a6cb37cbfacc', 'pembeli', '0'),
(9, 'fatimah zahra', '081211106741', 'fz49670@gmail.com', 'fzahra', '2bc8490e28d436db3c8aab80fbf07c14', 'pembeli', '1'),
(10, 'Raysa', '083829660159', 'raysaazzahra32@gmail.com', 'Raysa', 'e78bfcaba5e5341b69b1e195b06ad42e', 'pembeli', '0'),
(11, 'Kurniawan', '085342690115', 'wawanbds0707@gmail.com', 'Wawanbds', 'f2351db4ccf58fe42aca254d1d06bb1c', 'pembeli', '0'),
(12, 'iin hindawati', '081398588591', 'iinhindawati@gmail.com', 'iin hindawati', '2dc12ca8c6b8c3a9e158ce694ebb5c00', 'pembeli', '0'),
(13, 'Chang chang ', '081241064980 ', 'nurukhtunur@gmail.com', 'Chang chang ', '653d716345d8915046b904b90f41f271', 'pembeli', '0'),
(14, 'Kezia Adil', '082296894749', 'keziaadil502@gmail.com', 'Kezia', 'e07dfc72fa52cf432a67df35b1942887', 'pembeli', '0'),
(15, 'Kezia Adil', '082296894749', 'osinwatania@gmail.com', 'Kezia Adil', '8bba55f7be7ea9957360b57af484df3f', 'pembeli', '0'),
(16, 'Nina Maulina', '085719966975', 'ninaaulin6@gmail.com', 'Nina', '135ffb0b28567c060a8217df75a10c42', 'pembeli', '1'),
(17, 'Yulianti', '088289282822', 'Yyulianti43@gmail.com', 'Yulianti', '71774924d9f05f924f5706fb0e3c8614', 'pembeli', '0'),
(18, 'Indri lestari', '081288372644', 'adelsasa248@gmail.com', 'Indri lestari', '6251289e15f44a2a4fbe67180cfdc518', 'pembeli', '0'),
(19, 'Aurelya natasya thalia', '089696165735', 'aurellyanatasya141100@gmail.com', 'Aurell', '284436b793827d88b2daab34351f403d', 'pembeli', '0'),
(20, 'Dovino yanuar rizky pratama', '089696165735', 'dovinoyanuar22@gmail.com', 'Vino', '17df9db271eae86074f383e5c7dfd913', 'pembeli', '0'),
(21, 'Bambang saritomo', '085250329356', 'bambangsaritomo02@gmail.com', 'Bambang002', '2b5be9c116d6b69b5c49ae011c345712', 'pembeli', '1'),
(22, 'Rikaidayani', '083815395744', 'rikahandayani3945@gmail.com', 'Rikahandayani', '499f8a86024a923ff4a8caa49b7a1306', 'pembeli', '0'),
(23, 'Rikaidayani', '083815395744', 'rikaidayani177@gmail.com', 'Rikaidayani', '499f8a86024a923ff4a8caa49b7a1306', 'pembeli', '1'),
(24, 'Pungki widyawati ', '085728302727 ', 'Pungky.wdy@gmail.com', 'Widya ', '7b101b0b3dcd37fb64b77f8a374de851', 'pembeli', '1'),
(25, 'siti nur aini aisiyah', '082265177461', 'azwanuryanto2244@gmail.com', 'aisiyah', 'e7a3365541134436e51abe5580021d7e', 'pembeli', '0'),
(26, 'siti nur aini aisiyah', '082265177461', 'aisiyahyanto1144@gmail.com', 'aisiyah', 'e7a3365541134436e51abe5580021d7e', 'pembeli', '0'),
(27, 'Ika Indriani', '085846645255', 'ikaindriani927@gmail.com', 'Ika ', '8bd047d1757571a7959a1a750e9849d2', 'pembeli', '0'),
(28, 'Paulina octavia situmorang', '082294033442', 'paulimaoct@gmail.com', 'Faul442', '68cbfea9990c36af202cbc82f7f69781', 'pembeli', '1'),
(29, 'Nur afifah', '083806447151', 'afifahnur16067@gmail.com', 'Afifah', '22fb81e8d955e42957f447605fe4735d', 'pembeli', '0'),
(30, 'Akarim alhamid', '083181778110', 'akarim.alhamid@gmail.com', 'Akarim alhamid', 'f6de7775cecdf4f0e9f584d882d257d7', 'pembeli', '0'),
(31, 'Adityo Pratomo', '085777774460', 'adityo23.ap@gmail.com', 'adityo23', 'bc2fe6beabd703913593c2c4e9a1885f', 'pembeli', '0'),
(32, 'MaGeLLo\'Na Mall Online', '081354850678', 'muh.mursyididrus69@gmail.com', 'MaGeLLo\'Na Mall Online', '172b3e49dcdbafab36a944213fb2ffde', 'pembeli', '1'),
(33, 'SriWahyuni', '081554600594', 'sri13041993@gmail.com', 'SriWahYuni', '5db16024c036188cd902243f1a854466', 'pembeli', '0'),
(34, 'necklacediscoun', 'necklacediscoun', 'PrudenceAzic@yahoo.com', 'necklacediscoun', '55bcc1c59337488d0bbb0c703ed024c6', 'pembeli', '0'),
(35, 'mlmanmaxal', 'mlmanmaxal', 'przj377@163.com', 'mlmanmaxal', 'b88ec94e4a844ea019427756ee99dbaf', 'pembeli', '0'),
(36, 'ktrackeisid', 'ktrackeisid', 'ogsm626@163.com', 'ktrackeisid', '883bef23e55bcb77489a61b80b5c08f6', 'pembeli', '0'),
(37, 'itkonariknguye', 'itkonariknguye', 'a662862@163.com', 'itkonariknguye', 'fe49deb59b74e5d435bfaf4553fb44a8', 'pembeli', '0'),
(38, 'Hgv', '08542388569', 'rahmatdanil279@gmail.com', 'Danil297', 'ae4267d4d93a8165129fb4c9cc90ed06', 'pembeli', '0'),
(39, 'Bdbd', '6885808558', 'Jonihendra297@gmail.com', 'Jonihendra297', 'ae4267d4d93a8165129fb4c9cc90ed06', 'pembeli', '0'),
(40, 'Dalwansyah', '081277061804', 'julhamdalwansyah@gmail.com', 'Iwan', '9b4519999098f7795d945da1fb91f6e5', 'reseller', '0'),
(41, 'Saepul Anwar', '082325242564', 'aasaepul7@gmail.com', 'aasaepul', '6fe5ffcd105782504861cb610f31f044', 'pembeli', '1'),
(42, 'Karomahstore', '085211714558', 'karomahstoreofficial@gmail.com', 'karomahstore', 'dc0be0133fdac1c2dba042a6f62f079c', 'reseller', '1');

-- --------------------------------------------------------

--
-- Struktur dari tabel `tb_user_sosmed`
--

CREATE TABLE `tb_user_sosmed` (
  `id` int(11) NOT NULL,
  `oauth_provider` enum('','facebook','google','twitter') COLLATE utf8_unicode_ci NOT NULL,
  `oauth_uid` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `first_name` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `last_name` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `gender` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `picture` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `link` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=COMPACT;

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `tb_kategori`
--
ALTER TABLE `tb_kategori`
  ADD PRIMARY KEY (`id_kategori`);

--
-- Indeks untuk tabel `tb_login`
--
ALTER TABLE `tb_login`
  ADD PRIMARY KEY (`id_login`);

--
-- Indeks untuk tabel `tb_newsletter`
--
ALTER TABLE `tb_newsletter`
  ADD PRIMARY KEY (`id_newsletter`);

--
-- Indeks untuk tabel `tb_produk`
--
ALTER TABLE `tb_produk`
  ADD PRIMARY KEY (`id_produk`);

--
-- Indeks untuk tabel `tb_registrasi`
--
ALTER TABLE `tb_registrasi`
  ADD PRIMARY KEY (`id_registrasi`);

--
-- Indeks untuk tabel `tb_user_sosmed`
--
ALTER TABLE `tb_user_sosmed`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `tb_kategori`
--
ALTER TABLE `tb_kategori`
  MODIFY `id_kategori` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;

--
-- AUTO_INCREMENT untuk tabel `tb_login`
--
ALTER TABLE `tb_login`
  MODIFY `id_login` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT untuk tabel `tb_newsletter`
--
ALTER TABLE `tb_newsletter`
  MODIFY `id_newsletter` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT untuk tabel `tb_produk`
--
ALTER TABLE `tb_produk`
  MODIFY `id_produk` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=284;

--
-- AUTO_INCREMENT untuk tabel `tb_registrasi`
--
ALTER TABLE `tb_registrasi`
  MODIFY `id_registrasi` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=43;

--
-- AUTO_INCREMENT untuk tabel `tb_user_sosmed`
--
ALTER TABLE `tb_user_sosmed`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
